//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnocomWrapper.unicard.sdk.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://procemisorqachile:448/axis2SMU/services/CE_CECL0TL_SMUv10.CE_CECL0TL_SMUv" +
            "10HttpsSoap11Endpoint/")]
        public string tecnocom_sdk_AutorizadorLineas_CE_CECL0TL_SMUv10 {
            get {
                return ((string)(this["tecnocom_sdk_AutorizadorLineas_CE_CECL0TL_SMUv10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://procemisorqachile:448/axis2SMU/services/CE_CEMO0LT_SMUv10.CE_CEMO0LT_SMUv" +
            "10HttpsSoap11Endpoint/")]
        public string tecnocom_sdk_ModificacionLineaContrato_CE_CEMO0LT_SMUv10 {
            get {
                return ((string)(this["tecnocom_sdk_ModificacionLineaContrato_CE_CEMO0LT_SMUv10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://procemisorqachile:448/axis2SMU/services/CE_CECL0LS_SMUv10.CE_CECL0LS_SMUv" +
            "10HttpsSoap11Endpoint/")]
        public string TecnocomWrapper_unicard_sdk_ListaLimitesYSaldosPorReferencia_CE_CECL0LS_SMUv10 {
            get {
                return ((string)(this["TecnocomWrapper_unicard_sdk_ListaLimitesYSaldosPorReferencia_CE_CECL0LS_SMUv10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://procemisorchile:448/axis2SMU/services/CE_CECOURP_SMUv10.CE_CECOURP_SMUv" +
            "10HttpsSoap11Endpoint/")]
        public string TecnocomWrapper_unicard_sdk_ConsultaPansPorRut_CE_CECOURP_SMUv10 {
            get {
                return ((string)(this["TecnocomWrapper_unicard_sdk_ConsultaPansPorRut_CE_CECOURP_SMUv10"]));
            }
        }


        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string TecnocomWrapper_unicard_sdk_AcuseDeRecibo_CE_CEMO0RE_SMUv10
        {
            get
            {
                return ((string)(this["TecnocomWrapper_unicard_sdk_AcuseDeRecibo_CE_CEMO0RE_SMUv10"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://procemisorqachile:448/axis2SMU/services/CE_CECL0TC_SMUv10.CE_CECL0TC_SMUv" +
            "10HttpsSoap11Endpoint/")]
        public string TecnocomWrapper_unicard_sdk_RelacionTarjetasCuenta_CE_CECL0TC_SMUv10
        {
            get
            {
                return ((string)(this["TecnocomWrapper_unicard_sdk_RelacionTarjetasCuenta_CE_CECL0TC_SMUv10"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://procemisorchile:448/axis2SMU/services/CE_CECL0CO_v10?wsdl" +
            "10HttpsSoap11Endpoint/")]
        public string TecnocomWrapper_unicard_sdk_ConsultaMediosContactoPersona_CE_CECL0CO_v10
        {
            get
            {
                return ((string)(this["TecnocomWrapper_unicard_sdk_ConsultaMediosContactoPersona_CE_CECL0CO_v10"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://procemisorchile:448/axis2SMU/services/CE_CECO0P2_v10?wsdl" +
            "10HttpsSoap11Endpoint/")]
        public string TecnocomWrapper_unicard_sdk_BusquedaPersonasPorPan_CE_CECO0P2_v10
        {
            get
            {
                return ((string)(this["TecnocomWrapper_unicard_sdk_BusquedaPersonasPorPan_CE_CECO0P2_v10"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        public string TecnocomWrapper_unicard_sdk_PrePagoDiezDias_CE_CECO005_SMUv10
        {
            get
            {
                return ((string)(this["TecnocomWrapper_unicard_sdk_PrePagoDiezDias_CE_CECO005_SMUv10"]));
            }
        }
    }
}
