//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TecnocomWrapper.unicard.sdk.ListaLimitesYSaldosPorReferencia {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CE_CECL0LS_SMUv10Soap11Binding", Namespace="http://smu")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistroNewAge))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntradaExtendida))]
    public partial class CE_CECL0LS_SMUv10 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback echo_ServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback runServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CE_CECL0LS_SMUv10() {
            this.Url = global::TecnocomWrapper.unicard.sdk.Properties.Settings.Default.TecnocomWrapper_unicard_sdk_ListaLimitesYSaldosPorReferencia_CE_CECL0LS_SMUv10;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event echo_ServiceCompletedEventHandler echo_ServiceCompleted;
        
        /// <remarks/>
        public event runServiceCompletedEventHandler runServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:echo_Service", RequestNamespace="http://smu", ResponseNamespace="http://smu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string echo_Service() {
            object[] results = this.Invoke("echo_Service", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void echo_ServiceAsync() {
            this.echo_ServiceAsync(null);
        }
        
        /// <remarks/>
        public void echo_ServiceAsync(object userState) {
            if ((this.echo_ServiceOperationCompleted == null)) {
                this.echo_ServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.Onecho_ServiceOperationCompleted);
            }
            this.InvokeAsync("echo_Service", new object[0], this.echo_ServiceOperationCompleted, userState);
        }
        
        private void Onecho_ServiceOperationCompleted(object arg) {
            if ((this.echo_ServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.echo_ServiceCompleted(this, new echo_ServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:runService", RequestNamespace="http://smu", ResponseNamespace="http://smu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Respuesta_CECL0LS runService([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] OperationData opData, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Entrada_CECL0LS eEntrada) {
            object[] results = this.Invoke("runService", new object[] {
                        opData,
                        eEntrada});
            return ((Respuesta_CECL0LS)(results[0]));
        }
        
        /// <remarks/>
        public void runServiceAsync(OperationData opData, Entrada_CECL0LS eEntrada) {
            this.runServiceAsync(opData, eEntrada, null);
        }
        
        /// <remarks/>
        public void runServiceAsync(OperationData opData, Entrada_CECL0LS eEntrada, object userState) {
            if ((this.runServiceOperationCompleted == null)) {
                this.runServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrunServiceOperationCompleted);
            }
            this.InvokeAsync("runService", new object[] {
                        opData,
                        eEntrada}, this.runServiceOperationCompleted, userState);
        }
        
        private void OnrunServiceOperationCompleted(object arg) {
            if ((this.runServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.runServiceCompleted(this, new runServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class OperationData {
        
        private bool avanzarField;
        
        private bool avanzarFieldSpecified;
        
        private string canalField;
        
        private string claveFinField;
        
        private string claveInicioField;
        
        private string entidadField;
        
        private string idiomaField;
        
        private string pantPaginaField;
        
        private bool retrocederField;
        
        private bool retrocederFieldSpecified;
        
        private string securityHashField;
        
        /// <remarks/>
        public bool avanzar {
            get {
                return this.avanzarField;
            }
            set {
                this.avanzarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avanzarSpecified {
            get {
                return this.avanzarFieldSpecified;
            }
            set {
                this.avanzarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveFin {
            get {
                return this.claveFinField;
            }
            set {
                this.claveFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveInicio {
            get {
                return this.claveInicioField;
            }
            set {
                this.claveInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pantPagina {
            get {
                return this.pantPaginaField;
            }
            set {
                this.pantPaginaField = value;
            }
        }
        
        /// <remarks/>
        public bool retroceder {
            get {
                return this.retrocederField;
            }
            set {
                this.retrocederField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retrocederSpecified {
            get {
                return this.retrocederFieldSpecified;
            }
            set {
                this.retrocederFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string securityHash {
            get {
                return this.securityHashField;
            }
            set {
                this.securityHashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://formatos/xsd")]
    public partial class EaseDate {
        
        private int annoField;
        
        private bool annoFieldSpecified;
        
        private int diaField;
        
        private bool diaFieldSpecified;
        
        private string formatField;
        
        private int mesField;
        
        private bool mesFieldSpecified;
        
        private string nombreDiaField;
        
        private string nombreMesField;
        
        private string valueDateField;
        
        /// <remarks/>
        public int anno {
            get {
                return this.annoField;
            }
            set {
                this.annoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool annoSpecified {
            get {
                return this.annoFieldSpecified;
            }
            set {
                this.annoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaSpecified {
            get {
                return this.diaFieldSpecified;
            }
            set {
                this.diaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        public int mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mesSpecified {
            get {
                return this.mesFieldSpecified;
            }
            set {
                this.mesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombreDia {
            get {
                return this.nombreDiaField;
            }
            set {
                this.nombreDiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombreMes {
            get {
                return this.nombreMesField;
            }
            set {
                this.nombreMesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valueDate {
            get {
                return this.valueDateField;
            }
            set {
                this.valueDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta_CECL0LS_Registro_CECL0LS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class RegistroNewAge {
        
        private int registro_NumeroField;
        
        private bool registro_NumeroFieldSpecified;
        
        /// <remarks/>
        public int registro_Numero {
            get {
                return this.registro_NumeroField;
            }
            set {
                this.registro_NumeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool registro_NumeroSpecified {
            get {
                return this.registro_NumeroFieldSpecified;
            }
            set {
                this.registro_NumeroFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smu/xsd")]
    public partial class Respuesta_CECL0LS_Registro_CECL0LS : RegistroNewAge {
        
        private int clamonField;
        
        private bool clamonFieldSpecified;
        
        private string contcurField;
        
        private string desindporlimField;
        
        private string desmonField;
        
        private EaseDate fecaltaField;
        
        private EaseDate fecfinField;
        
        private EaseDate feciniField;
        
        private string indporlimField;
        
        private string indvigField;
        
        private double limcrelinField;
        
        private bool limcrelinFieldSpecified;
        
        private int linref2Field;
        
        private bool linref2FieldSpecified;
        
        private int porlimField;
        
        private bool porlimFieldSpecified;
        
        private double salautlinField;
        
        private bool salautlinFieldSpecified;
        
        private double saldislinField;
        
        private bool saldislinFieldSpecified;
        
        private string tipolinField;
        
        /// <remarks/>
        public int clamon {
            get {
                return this.clamonField;
            }
            set {
                this.clamonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clamonSpecified {
            get {
                return this.clamonFieldSpecified;
            }
            set {
                this.clamonFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string contcur {
            get {
                return this.contcurField;
            }
            set {
                this.contcurField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desindporlim {
            get {
                return this.desindporlimField;
            }
            set {
                this.desindporlimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desmon {
            get {
                return this.desmonField;
            }
            set {
                this.desmonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EaseDate fecalta {
            get {
                return this.fecaltaField;
            }
            set {
                this.fecaltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EaseDate fecfin {
            get {
                return this.fecfinField;
            }
            set {
                this.fecfinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EaseDate fecini {
            get {
                return this.feciniField;
            }
            set {
                this.feciniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string indporlim {
            get {
                return this.indporlimField;
            }
            set {
                this.indporlimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string indvig {
            get {
                return this.indvigField;
            }
            set {
                this.indvigField = value;
            }
        }
        
        /// <remarks/>
        public double limcrelin {
            get {
                return this.limcrelinField;
            }
            set {
                this.limcrelinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool limcrelinSpecified {
            get {
                return this.limcrelinFieldSpecified;
            }
            set {
                this.limcrelinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int linref2 {
            get {
                return this.linref2Field;
            }
            set {
                this.linref2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool linref2Specified {
            get {
                return this.linref2FieldSpecified;
            }
            set {
                this.linref2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int porlim {
            get {
                return this.porlimField;
            }
            set {
                this.porlimField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool porlimSpecified {
            get {
                return this.porlimFieldSpecified;
            }
            set {
                this.porlimFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double salautlin {
            get {
                return this.salautlinField;
            }
            set {
                this.salautlinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool salautlinSpecified {
            get {
                return this.salautlinFieldSpecified;
            }
            set {
                this.salautlinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double saldislin {
            get {
                return this.saldislinField;
            }
            set {
                this.saldislinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool saldislinSpecified {
            get {
                return this.saldislinFieldSpecified;
            }
            set {
                this.saldislinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipolin {
            get {
                return this.tipolinField;
            }
            set {
                this.tipolinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta_CECL0LS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class Respuesta {
        
        private string claveFinField;
        
        private string claveInicioField;
        
        private string descRetornoField;
        
        private string indMasDatosField;
        
        private string pantPaginaField;
        
        private string retornoField;
        
        private string securityTokenField;
        
        private string tiempoEjecucionField;
        
        private int totalRegistrosField;
        
        private bool totalRegistrosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveFin {
            get {
                return this.claveFinField;
            }
            set {
                this.claveFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveInicio {
            get {
                return this.claveInicioField;
            }
            set {
                this.claveInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descRetorno {
            get {
                return this.descRetornoField;
            }
            set {
                this.descRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string indMasDatos {
            get {
                return this.indMasDatosField;
            }
            set {
                this.indMasDatosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pantPagina {
            get {
                return this.pantPaginaField;
            }
            set {
                this.pantPaginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string securityToken {
            get {
                return this.securityTokenField;
            }
            set {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tiempoEjecucion {
            get {
                return this.tiempoEjecucionField;
            }
            set {
                this.tiempoEjecucionField = value;
            }
        }
        
        /// <remarks/>
        public int totalRegistros {
            get {
                return this.totalRegistrosField;
            }
            set {
                this.totalRegistrosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalRegistrosSpecified {
            get {
                return this.totalRegistrosFieldSpecified;
            }
            set {
                this.totalRegistrosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smu/xsd")]
    public partial class Respuesta_CECL0LS : Respuesta {
        
        private Respuesta_CECL0LS_Registro_CECL0LS[] contratosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contratos", IsNullable=true)]
        public Respuesta_CECL0LS_Registro_CECL0LS[] contratos {
            get {
                return this.contratosField;
            }
            set {
                this.contratosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entrada_CECL0LS))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class EntradaExtendida {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smu/xsd")]
    public partial class Entrada_CECL0LS : EntradaExtendida {
        
        private string centaltaField;
        
        private string cuentaField;
        
        private int linrefField;
        
        private bool linrefFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string centalta {
            get {
                return this.centaltaField;
            }
            set {
                this.centaltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        public int linref {
            get {
                return this.linrefField;
            }
            set {
                this.linrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool linrefSpecified {
            get {
                return this.linrefFieldSpecified;
            }
            set {
                this.linrefFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void echo_ServiceCompletedEventHandler(object sender, echo_ServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class echo_ServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal echo_ServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void runServiceCompletedEventHandler(object sender, runServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class runServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal runServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta_CECL0LS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta_CECL0LS)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591