//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TecnocomWrapper.unicard.sdk.ConsultaPansPorRut {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CE_CECOURP_SMUv10Soap11Binding", Namespace="http://smu")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistroNewAge))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntradaExtendida))]
    public partial class CE_CECOURP_SMUv10 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback runServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback echo_ServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CE_CECOURP_SMUv10() {
            this.Url = global::TecnocomWrapper.unicard.sdk.Properties.Settings.Default.TecnocomWrapper_unicard_sdk_ConsultaPansPorRut_CE_CECOURP_SMUv10;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event runServiceCompletedEventHandler runServiceCompleted;
        
        /// <remarks/>
        public event echo_ServiceCompletedEventHandler echo_ServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:runService", RequestNamespace="http://smu", ResponseNamespace="http://smu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Respuesta_CECOURP runService([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] OperationData opData, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Entrada_CECOURP eEntrada) {
            object[] results = this.Invoke("runService", new object[] {
                        opData,
                        eEntrada});
            return ((Respuesta_CECOURP)(results[0]));
        }
        
        /// <remarks/>
        public void runServiceAsync(OperationData opData, Entrada_CECOURP eEntrada) {
            this.runServiceAsync(opData, eEntrada, null);
        }
        
        /// <remarks/>
        public void runServiceAsync(OperationData opData, Entrada_CECOURP eEntrada, object userState) {
            if ((this.runServiceOperationCompleted == null)) {
                this.runServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrunServiceOperationCompleted);
            }
            this.InvokeAsync("runService", new object[] {
                        opData,
                        eEntrada}, this.runServiceOperationCompleted, userState);
        }
        
        private void OnrunServiceOperationCompleted(object arg) {
            if ((this.runServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.runServiceCompleted(this, new runServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:echo_Service", RequestNamespace="http://smu", ResponseNamespace="http://smu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string echo_Service() {
            object[] results = this.Invoke("echo_Service", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void echo_ServiceAsync() {
            this.echo_ServiceAsync(null);
        }
        
        /// <remarks/>
        public void echo_ServiceAsync(object userState) {
            if ((this.echo_ServiceOperationCompleted == null)) {
                this.echo_ServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.Onecho_ServiceOperationCompleted);
            }
            this.InvokeAsync("echo_Service", new object[0], this.echo_ServiceOperationCompleted, userState);
        }
        
        private void Onecho_ServiceOperationCompleted(object arg) {
            if ((this.echo_ServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.echo_ServiceCompleted(this, new echo_ServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class OperationData {
        
        private bool avanzarField;
        
        private bool avanzarFieldSpecified;
        
        private string canalField;
        
        private string claveFinField;
        
        private string claveInicioField;
        
        private string entidadField;
        
        private string idiomaField;
        
        private string pantPaginaField;
        
        private bool retrocederField;
        
        private bool retrocederFieldSpecified;
        
        private string securityHashField;
        
        /// <remarks/>
        public bool avanzar {
            get {
                return this.avanzarField;
            }
            set {
                this.avanzarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avanzarSpecified {
            get {
                return this.avanzarFieldSpecified;
            }
            set {
                this.avanzarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveFin {
            get {
                return this.claveFinField;
            }
            set {
                this.claveFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveInicio {
            get {
                return this.claveInicioField;
            }
            set {
                this.claveInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pantPagina {
            get {
                return this.pantPaginaField;
            }
            set {
                this.pantPaginaField = value;
            }
        }
        
        /// <remarks/>
        public bool retroceder {
            get {
                return this.retrocederField;
            }
            set {
                this.retrocederField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retrocederSpecified {
            get {
                return this.retrocederFieldSpecified;
            }
            set {
                this.retrocederFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string securityHash {
            get {
                return this.securityHashField;
            }
            set {
                this.securityHashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta_CECOURP_Registro_CECOURP))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class RegistroNewAge {
        
        private int registro_NumeroField;
        
        private bool registro_NumeroFieldSpecified;
        
        /// <remarks/>
        public int registro_Numero {
            get {
                return this.registro_NumeroField;
            }
            set {
                this.registro_NumeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool registro_NumeroSpecified {
            get {
                return this.registro_NumeroFieldSpecified;
            }
            set {
                this.registro_NumeroFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smu/xsd")]
    public partial class Respuesta_CECOURP_Registro_CECOURP : RegistroNewAge {
        
        private string calpartField;
        
        private string centaltaField;
        
        private string codentField;
        
        private int codmarField;
        
        private bool codmarFieldSpecified;
        
        private string cuentaField;
        
        private int indtiptField;
        
        private bool indtiptFieldSpecified;
        
        private int numbenctaField;
        
        private bool numbenctaFieldSpecified;
        
        private string numdocField;
        
        private string panField;
        
        private string tipdocField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string calpart {
            get {
                return this.calpartField;
            }
            set {
                this.calpartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string centalta {
            get {
                return this.centaltaField;
            }
            set {
                this.centaltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codent {
            get {
                return this.codentField;
            }
            set {
                this.codentField = value;
            }
        }
        
        /// <remarks/>
        public int codmar {
            get {
                return this.codmarField;
            }
            set {
                this.codmarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codmarSpecified {
            get {
                return this.codmarFieldSpecified;
            }
            set {
                this.codmarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        public int indtipt {
            get {
                return this.indtiptField;
            }
            set {
                this.indtiptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indtiptSpecified {
            get {
                return this.indtiptFieldSpecified;
            }
            set {
                this.indtiptFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int numbencta {
            get {
                return this.numbenctaField;
            }
            set {
                this.numbenctaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numbenctaSpecified {
            get {
                return this.numbenctaFieldSpecified;
            }
            set {
                this.numbenctaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numdoc {
            get {
                return this.numdocField;
            }
            set {
                this.numdocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pan {
            get {
                return this.panField;
            }
            set {
                this.panField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipdoc {
            get {
                return this.tipdocField;
            }
            set {
                this.tipdocField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta_CECOURP))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class Respuesta {
        
        private string claveFinField;
        
        private string claveInicioField;
        
        private string descRetornoField;
        
        private string indMasDatosField;
        
        private string pantPaginaField;
        
        private string retornoField;
        
        private string securityTokenField;
        
        private string tiempoEjecucionField;
        
        private int totalRegistrosField;
        
        private bool totalRegistrosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveFin {
            get {
                return this.claveFinField;
            }
            set {
                this.claveFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveInicio {
            get {
                return this.claveInicioField;
            }
            set {
                this.claveInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descRetorno {
            get {
                return this.descRetornoField;
            }
            set {
                this.descRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string indMasDatos {
            get {
                return this.indMasDatosField;
            }
            set {
                this.indMasDatosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pantPagina {
            get {
                return this.pantPaginaField;
            }
            set {
                this.pantPaginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string securityToken {
            get {
                return this.securityTokenField;
            }
            set {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tiempoEjecucion {
            get {
                return this.tiempoEjecucionField;
            }
            set {
                this.tiempoEjecucionField = value;
            }
        }
        
        /// <remarks/>
        public int totalRegistros {
            get {
                return this.totalRegistrosField;
            }
            set {
                this.totalRegistrosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalRegistrosSpecified {
            get {
                return this.totalRegistrosFieldSpecified;
            }
            set {
                this.totalRegistrosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smu/xsd")]
    public partial class Respuesta_CECOURP : Respuesta {
        
        private Respuesta_CECOURP_Registro_CECOURP[] contratosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contratos", IsNullable=true)]
        public Respuesta_CECOURP_Registro_CECOURP[] contratos {
            get {
                return this.contratosField;
            }
            set {
                this.contratosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entrada_CECOURP))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class EntradaExtendida {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smu/xsd")]
    public partial class Entrada_CECOURP : EntradaExtendida {
        
        private string docupanField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string docupan {
            get {
                return this.docupanField;
            }
            set {
                this.docupanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void runServiceCompletedEventHandler(object sender, runServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class runServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal runServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta_CECOURP Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta_CECOURP)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void echo_ServiceCompletedEventHandler(object sender, echo_ServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class echo_ServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal echo_ServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591