//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TecnocomWrapper.unicard.sdk.PrePagoDiezDias {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CE_CECO005_SMUv10Soap11Binding", Namespace="http://smu")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistroNewAge))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntradaExtendida))]
    public partial class CE_CECO005_SMUv10 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback echo_ServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback runServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CE_CECO005_SMUv10() {
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event echo_ServiceCompletedEventHandler echo_ServiceCompleted;
        
        /// <remarks/>
        public event runServiceCompletedEventHandler runServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:echo_Service", RequestNamespace="http://smu", ResponseNamespace="http://smu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string echo_Service() {
            object[] results = this.Invoke("echo_Service", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void echo_ServiceAsync() {
            this.echo_ServiceAsync(null);
        }
        
        /// <remarks/>
        public void echo_ServiceAsync(object userState) {
            if ((this.echo_ServiceOperationCompleted == null)) {
                this.echo_ServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.Onecho_ServiceOperationCompleted);
            }
            this.InvokeAsync("echo_Service", new object[0], this.echo_ServiceOperationCompleted, userState);
        }
        
        private void Onecho_ServiceOperationCompleted(object arg) {
            if ((this.echo_ServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.echo_ServiceCompleted(this, new echo_ServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:runService", RequestNamespace="http://smu", ResponseNamespace="http://smu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Respuesta_CECO005 runService([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] OperationData opData, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Entrada_CECO005 eEntrada) {
            object[] results = this.Invoke("runService", new object[] {
                        opData,
                        eEntrada});
            return ((Respuesta_CECO005)(results[0]));
        }
        
        /// <remarks/>
        public void runServiceAsync(OperationData opData, Entrada_CECO005 eEntrada) {
            this.runServiceAsync(opData, eEntrada, null);
        }
        
        /// <remarks/>
        public void runServiceAsync(OperationData opData, Entrada_CECO005 eEntrada, object userState) {
            if ((this.runServiceOperationCompleted == null)) {
                this.runServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrunServiceOperationCompleted);
            }
            this.InvokeAsync("runService", new object[] {
                        opData,
                        eEntrada}, this.runServiceOperationCompleted, userState);
        }
        
        private void OnrunServiceOperationCompleted(object arg) {
            if ((this.runServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.runServiceCompleted(this, new runServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class OperationData {
        
        private bool avanzarField;
        
        private bool avanzarFieldSpecified;
        
        private string canalField;
        
        private string claveFinField;
        
        private string claveInicioField;
        
        private string entidadField;
        
        private string idiomaField;
        
        private string pantPaginaField;
        
        private bool retrocederField;
        
        private bool retrocederFieldSpecified;
        
        private string securityHashField;
        
        /// <remarks/>
        public bool avanzar {
            get {
                return this.avanzarField;
            }
            set {
                this.avanzarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avanzarSpecified {
            get {
                return this.avanzarFieldSpecified;
            }
            set {
                this.avanzarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveFin {
            get {
                return this.claveFinField;
            }
            set {
                this.claveFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveInicio {
            get {
                return this.claveInicioField;
            }
            set {
                this.claveInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pantPagina {
            get {
                return this.pantPaginaField;
            }
            set {
                this.pantPaginaField = value;
            }
        }
        
        /// <remarks/>
        public bool retroceder {
            get {
                return this.retrocederField;
            }
            set {
                this.retrocederField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retrocederSpecified {
            get {
                return this.retrocederFieldSpecified;
            }
            set {
                this.retrocederFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string securityHash {
            get {
                return this.securityHashField;
            }
            set {
                this.securityHashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta_CECO005_Registro_CECO005))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class RegistroNewAge {
        
        private int registro_NumeroField;
        
        private bool registro_NumeroFieldSpecified;
        
        /// <remarks/>
        public int registro_Numero {
            get {
                return this.registro_NumeroField;
            }
            set {
                this.registro_NumeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool registro_NumeroSpecified {
            get {
                return this.registro_NumeroFieldSpecified;
            }
            set {
                this.registro_NumeroFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smu/xsd")]
    public partial class Respuesta_CECO005_Registro_CECO005 : RegistroNewAge {
        
        private double bonmes1Field;
        
        private bool bonmes1FieldSpecified;
        
        private double bonmes2Field;
        
        private bool bonmes2FieldSpecified;
        
        private double comis_prepagoField;
        
        private bool comis_prepagoFieldSpecified;
        
        private double dcocuo1Field;
        
        private bool dcocuo1FieldSpecified;
        
        private double dcocuo2Field;
        
        private bool dcocuo2FieldSpecified;
        
        private double dcuper1Field;
        
        private bool dcuper1FieldSpecified;
        
        private double dcuper2Field;
        
        private bool dcuper2FieldSpecified;
        
        private double descuentoField;
        
        private bool descuentoFieldSpecified;
        
        private double deuda_morosaField;
        
        private bool deuda_morosaFieldSpecified;
        
        private double dtotal1Field;
        
        private bool dtotal1FieldSpecified;
        
        private double dtotal2Field;
        
        private bool dtotal2FieldSpecified;
        
        private double intdev1Field;
        
        private bool intdev1FieldSpecified;
        
        private double intdev2Field;
        
        private bool intdev2FieldSpecified;
        
        private double intere1Field;
        
        private bool intere1FieldSpecified;
        
        private double intere2Field;
        
        private bool intere2FieldSpecified;
        
        private double mesact1Field;
        
        private bool mesact1FieldSpecified;
        
        private double mesact2Field;
        
        private bool mesact2FieldSpecified;
        
        private double monto_prepagoField;
        
        private bool monto_prepagoFieldSpecified;
        
        private double recemi1Field;
        
        private bool recemi1FieldSpecified;
        
        private double recemi2Field;
        
        private bool recemi2FieldSpecified;
        
        private double salact1Field;
        
        private bool salact1FieldSpecified;
        
        private double salact2Field;
        
        private bool salact2FieldSpecified;
        
        private string saldautoField;
        
        private double saldis1Field;
        
        private bool saldis1FieldSpecified;
        
        private double saldis2Field;
        
        private bool saldis2FieldSpecified;
        
        private double salimp1Field;
        
        private bool salimp1FieldSpecified;
        
        private double salimp2Field;
        
        private bool salimp2FieldSpecified;
        
        private double totalField;
        
        private bool totalFieldSpecified;
        
        /// <remarks/>
        public double bonmes1 {
            get {
                return this.bonmes1Field;
            }
            set {
                this.bonmes1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bonmes1Specified {
            get {
                return this.bonmes1FieldSpecified;
            }
            set {
                this.bonmes1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double bonmes2 {
            get {
                return this.bonmes2Field;
            }
            set {
                this.bonmes2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bonmes2Specified {
            get {
                return this.bonmes2FieldSpecified;
            }
            set {
                this.bonmes2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double comis_prepago {
            get {
                return this.comis_prepagoField;
            }
            set {
                this.comis_prepagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool comis_prepagoSpecified {
            get {
                return this.comis_prepagoFieldSpecified;
            }
            set {
                this.comis_prepagoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double dcocuo1 {
            get {
                return this.dcocuo1Field;
            }
            set {
                this.dcocuo1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dcocuo1Specified {
            get {
                return this.dcocuo1FieldSpecified;
            }
            set {
                this.dcocuo1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double dcocuo2 {
            get {
                return this.dcocuo2Field;
            }
            set {
                this.dcocuo2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dcocuo2Specified {
            get {
                return this.dcocuo2FieldSpecified;
            }
            set {
                this.dcocuo2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double dcuper1 {
            get {
                return this.dcuper1Field;
            }
            set {
                this.dcuper1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dcuper1Specified {
            get {
                return this.dcuper1FieldSpecified;
            }
            set {
                this.dcuper1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double dcuper2 {
            get {
                return this.dcuper2Field;
            }
            set {
                this.dcuper2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dcuper2Specified {
            get {
                return this.dcuper2FieldSpecified;
            }
            set {
                this.dcuper2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool descuentoSpecified {
            get {
                return this.descuentoFieldSpecified;
            }
            set {
                this.descuentoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double deuda_morosa {
            get {
                return this.deuda_morosaField;
            }
            set {
                this.deuda_morosaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deuda_morosaSpecified {
            get {
                return this.deuda_morosaFieldSpecified;
            }
            set {
                this.deuda_morosaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double dtotal1 {
            get {
                return this.dtotal1Field;
            }
            set {
                this.dtotal1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtotal1Specified {
            get {
                return this.dtotal1FieldSpecified;
            }
            set {
                this.dtotal1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double dtotal2 {
            get {
                return this.dtotal2Field;
            }
            set {
                this.dtotal2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtotal2Specified {
            get {
                return this.dtotal2FieldSpecified;
            }
            set {
                this.dtotal2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double intdev1 {
            get {
                return this.intdev1Field;
            }
            set {
                this.intdev1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool intdev1Specified {
            get {
                return this.intdev1FieldSpecified;
            }
            set {
                this.intdev1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double intdev2 {
            get {
                return this.intdev2Field;
            }
            set {
                this.intdev2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool intdev2Specified {
            get {
                return this.intdev2FieldSpecified;
            }
            set {
                this.intdev2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double intere1 {
            get {
                return this.intere1Field;
            }
            set {
                this.intere1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool intere1Specified {
            get {
                return this.intere1FieldSpecified;
            }
            set {
                this.intere1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double intere2 {
            get {
                return this.intere2Field;
            }
            set {
                this.intere2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool intere2Specified {
            get {
                return this.intere2FieldSpecified;
            }
            set {
                this.intere2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double mesact1 {
            get {
                return this.mesact1Field;
            }
            set {
                this.mesact1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mesact1Specified {
            get {
                return this.mesact1FieldSpecified;
            }
            set {
                this.mesact1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double mesact2 {
            get {
                return this.mesact2Field;
            }
            set {
                this.mesact2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mesact2Specified {
            get {
                return this.mesact2FieldSpecified;
            }
            set {
                this.mesact2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double monto_prepago {
            get {
                return this.monto_prepagoField;
            }
            set {
                this.monto_prepagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monto_prepagoSpecified {
            get {
                return this.monto_prepagoFieldSpecified;
            }
            set {
                this.monto_prepagoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double recemi1 {
            get {
                return this.recemi1Field;
            }
            set {
                this.recemi1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recemi1Specified {
            get {
                return this.recemi1FieldSpecified;
            }
            set {
                this.recemi1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double recemi2 {
            get {
                return this.recemi2Field;
            }
            set {
                this.recemi2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recemi2Specified {
            get {
                return this.recemi2FieldSpecified;
            }
            set {
                this.recemi2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double salact1 {
            get {
                return this.salact1Field;
            }
            set {
                this.salact1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool salact1Specified {
            get {
                return this.salact1FieldSpecified;
            }
            set {
                this.salact1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double salact2 {
            get {
                return this.salact2Field;
            }
            set {
                this.salact2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool salact2Specified {
            get {
                return this.salact2FieldSpecified;
            }
            set {
                this.salact2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string saldauto {
            get {
                return this.saldautoField;
            }
            set {
                this.saldautoField = value;
            }
        }
        
        /// <remarks/>
        public double saldis1 {
            get {
                return this.saldis1Field;
            }
            set {
                this.saldis1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool saldis1Specified {
            get {
                return this.saldis1FieldSpecified;
            }
            set {
                this.saldis1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double saldis2 {
            get {
                return this.saldis2Field;
            }
            set {
                this.saldis2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool saldis2Specified {
            get {
                return this.saldis2FieldSpecified;
            }
            set {
                this.saldis2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double salimp1 {
            get {
                return this.salimp1Field;
            }
            set {
                this.salimp1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool salimp1Specified {
            get {
                return this.salimp1FieldSpecified;
            }
            set {
                this.salimp1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double salimp2 {
            get {
                return this.salimp2Field;
            }
            set {
                this.salimp2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool salimp2Specified {
            get {
                return this.salimp2FieldSpecified;
            }
            set {
                this.salimp2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalSpecified {
            get {
                return this.totalFieldSpecified;
            }
            set {
                this.totalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta_CECO005))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class Respuesta {
        
        private string claveFinField;
        
        private string claveInicioField;
        
        private string descRetornoField;
        
        private string indMasDatosField;
        
        private string pantPaginaField;
        
        private string retornoField;
        
        private string securityTokenField;
        
        private string tiempoEjecucionField;
        
        private int totalRegistrosField;
        
        private bool totalRegistrosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveFin {
            get {
                return this.claveFinField;
            }
            set {
                this.claveFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveInicio {
            get {
                return this.claveInicioField;
            }
            set {
                this.claveInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descRetorno {
            get {
                return this.descRetornoField;
            }
            set {
                this.descRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string indMasDatos {
            get {
                return this.indMasDatosField;
            }
            set {
                this.indMasDatosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pantPagina {
            get {
                return this.pantPaginaField;
            }
            set {
                this.pantPaginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string securityToken {
            get {
                return this.securityTokenField;
            }
            set {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tiempoEjecucion {
            get {
                return this.tiempoEjecucionField;
            }
            set {
                this.tiempoEjecucionField = value;
            }
        }
        
        /// <remarks/>
        public int totalRegistros {
            get {
                return this.totalRegistrosField;
            }
            set {
                this.totalRegistrosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalRegistrosSpecified {
            get {
                return this.totalRegistrosFieldSpecified;
            }
            set {
                this.totalRegistrosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smu/xsd")]
    public partial class Respuesta_CECO005 : Respuesta {
        
        private Respuesta_CECO005_Registro_CECO005[] contratosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contratos", IsNullable=true)]
        public Respuesta_CECO005_Registro_CECO005[] contratos {
            get {
                return this.contratosField;
            }
            set {
                this.contratosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entrada_CECO005))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class EntradaExtendida {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smu/xsd")]
    public partial class Entrada_CECO005 : EntradaExtendida {
        
        private string centaltaField;
        
        private int clamon1Field;
        
        private bool clamon1FieldSpecified;
        
        private int clamon2Field;
        
        private bool clamon2FieldSpecified;
        
        private string cuentaField;
        
        private string panField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string centalta {
            get {
                return this.centaltaField;
            }
            set {
                this.centaltaField = value;
            }
        }
        
        /// <remarks/>
        public int clamon1 {
            get {
                return this.clamon1Field;
            }
            set {
                this.clamon1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clamon1Specified {
            get {
                return this.clamon1FieldSpecified;
            }
            set {
                this.clamon1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int clamon2 {
            get {
                return this.clamon2Field;
            }
            set {
                this.clamon2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool clamon2Specified {
            get {
                return this.clamon2FieldSpecified;
            }
            set {
                this.clamon2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pan {
            get {
                return this.panField;
            }
            set {
                this.panField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void echo_ServiceCompletedEventHandler(object sender, echo_ServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class echo_ServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal echo_ServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void runServiceCompletedEventHandler(object sender, runServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class runServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal runServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta_CECO005 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta_CECO005)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591