//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TecnocomWrapper.unicard.sdk.RelacionTarjetasCuenta {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CE_CECL0TC_SMUv10Soap11Binding", Namespace="http://smu")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistroNewAge))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntradaExtendida))]
    public partial class CE_CECL0TC_SMUv10 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback runServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback echo_ServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CE_CECL0TC_SMUv10() {
            this.Url = global::TecnocomWrapper.unicard.sdk.Properties.Settings.Default.TecnocomWrapper_unicard_sdk_RelacionTarjetasCuenta_CE_CECL0TC_SMUv10;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event runServiceCompletedEventHandler runServiceCompleted;
        
        /// <remarks/>
        public event echo_ServiceCompletedEventHandler echo_ServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:runService", RequestNamespace="http://smu", ResponseNamespace="http://smu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Respuesta_CECL0TC runService([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] OperationData opData, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Entrada_CECL0TC eEntrada) {
            object[] results = this.Invoke("runService", new object[] {
                        opData,
                        eEntrada});
            return ((Respuesta_CECL0TC)(results[0]));
        }
        
        /// <remarks/>
        public void runServiceAsync(OperationData opData, Entrada_CECL0TC eEntrada) {
            this.runServiceAsync(opData, eEntrada, null);
        }
        
        /// <remarks/>
        public void runServiceAsync(OperationData opData, Entrada_CECL0TC eEntrada, object userState) {
            if ((this.runServiceOperationCompleted == null)) {
                this.runServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrunServiceOperationCompleted);
            }
            this.InvokeAsync("runService", new object[] {
                        opData,
                        eEntrada}, this.runServiceOperationCompleted, userState);
        }
        
        private void OnrunServiceOperationCompleted(object arg) {
            if ((this.runServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.runServiceCompleted(this, new runServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:echo_Service", RequestNamespace="http://smu", ResponseNamespace="http://smu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string echo_Service() {
            object[] results = this.Invoke("echo_Service", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void echo_ServiceAsync() {
            this.echo_ServiceAsync(null);
        }
        
        /// <remarks/>
        public void echo_ServiceAsync(object userState) {
            if ((this.echo_ServiceOperationCompleted == null)) {
                this.echo_ServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.Onecho_ServiceOperationCompleted);
            }
            this.InvokeAsync("echo_Service", new object[0], this.echo_ServiceOperationCompleted, userState);
        }
        
        private void Onecho_ServiceOperationCompleted(object arg) {
            if ((this.echo_ServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.echo_ServiceCompleted(this, new echo_ServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class OperationData {
        
        private bool avanzarField;
        
        private bool avanzarFieldSpecified;
        
        private string canalField;
        
        private string claveFinField;
        
        private string claveInicioField;
        
        private string entidadField;
        
        private string idiomaField;
        
        private string pantPaginaField;
        
        private bool retrocederField;
        
        private bool retrocederFieldSpecified;
        
        private string securityHashField;
        
        /// <remarks/>
        public bool avanzar {
            get {
                return this.avanzarField;
            }
            set {
                this.avanzarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avanzarSpecified {
            get {
                return this.avanzarFieldSpecified;
            }
            set {
                this.avanzarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveFin {
            get {
                return this.claveFinField;
            }
            set {
                this.claveFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveInicio {
            get {
                return this.claveInicioField;
            }
            set {
                this.claveInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pantPagina {
            get {
                return this.pantPaginaField;
            }
            set {
                this.pantPaginaField = value;
            }
        }
        
        /// <remarks/>
        public bool retroceder {
            get {
                return this.retrocederField;
            }
            set {
                this.retrocederField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retrocederSpecified {
            get {
                return this.retrocederFieldSpecified;
            }
            set {
                this.retrocederFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string securityHash {
            get {
                return this.securityHashField;
            }
            set {
                this.securityHashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://formatos/xsd")]
    public partial class EaseDate {
        
        private int annoField;
        
        private bool annoFieldSpecified;
        
        private int diaField;
        
        private bool diaFieldSpecified;
        
        private string formatField;
        
        private int mesField;
        
        private bool mesFieldSpecified;
        
        private string nombreDiaField;
        
        private string nombreMesField;
        
        private string valueDateField;
        
        /// <remarks/>
        public int anno {
            get {
                return this.annoField;
            }
            set {
                this.annoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool annoSpecified {
            get {
                return this.annoFieldSpecified;
            }
            set {
                this.annoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diaSpecified {
            get {
                return this.diaFieldSpecified;
            }
            set {
                this.diaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        public int mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mesSpecified {
            get {
                return this.mesFieldSpecified;
            }
            set {
                this.mesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombreDia {
            get {
                return this.nombreDiaField;
            }
            set {
                this.nombreDiaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombreMes {
            get {
                return this.nombreMesField;
            }
            set {
                this.nombreMesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valueDate {
            get {
                return this.valueDateField;
            }
            set {
                this.valueDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta_CECL0TC_Registro_CECL0TC))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class RegistroNewAge {
        
        private int registro_NumeroField;
        
        private bool registro_NumeroFieldSpecified;
        
        /// <remarks/>
        public int registro_Numero {
            get {
                return this.registro_NumeroField;
            }
            set {
                this.registro_NumeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool registro_NumeroSpecified {
            get {
                return this.registro_NumeroFieldSpecified;
            }
            set {
                this.registro_NumeroFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smu/xsd")]
    public partial class Respuesta_CECL0TC_Registro_CECL0TC : RegistroNewAge {
        
        private int codblqField;
        
        private bool codblqFieldSpecified;
        
        private int codmarField;
        
        private bool codmarFieldSpecified;
        
        private string desblqredField;
        
        private string desmarredField;
        
        private string dessittarField;
        
        private string destiptredField;
        
        private EaseDate fecaltaField;
        
        private EaseDate fecbajaField;
        
        private int indsittarField;
        
        private bool indsittarFieldSpecified;
        
        private int indtiptField;
        
        private bool indtiptFieldSpecified;
        
        private string nombenredField;
        
        private int numbenctaField;
        
        private bool numbenctaFieldSpecified;
        
        private long numplasticoField;
        
        private bool numplasticoFieldSpecified;
        
        private string panField;
        
        /// <remarks/>
        public int codblq {
            get {
                return this.codblqField;
            }
            set {
                this.codblqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codblqSpecified {
            get {
                return this.codblqFieldSpecified;
            }
            set {
                this.codblqFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int codmar {
            get {
                return this.codmarField;
            }
            set {
                this.codmarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codmarSpecified {
            get {
                return this.codmarFieldSpecified;
            }
            set {
                this.codmarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desblqred {
            get {
                return this.desblqredField;
            }
            set {
                this.desblqredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desmarred {
            get {
                return this.desmarredField;
            }
            set {
                this.desmarredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string dessittar {
            get {
                return this.dessittarField;
            }
            set {
                this.dessittarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string destiptred {
            get {
                return this.destiptredField;
            }
            set {
                this.destiptredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EaseDate fecalta {
            get {
                return this.fecaltaField;
            }
            set {
                this.fecaltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EaseDate fecbaja {
            get {
                return this.fecbajaField;
            }
            set {
                this.fecbajaField = value;
            }
        }
        
        /// <remarks/>
        public int indsittar {
            get {
                return this.indsittarField;
            }
            set {
                this.indsittarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indsittarSpecified {
            get {
                return this.indsittarFieldSpecified;
            }
            set {
                this.indsittarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int indtipt {
            get {
                return this.indtiptField;
            }
            set {
                this.indtiptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indtiptSpecified {
            get {
                return this.indtiptFieldSpecified;
            }
            set {
                this.indtiptFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombenred {
            get {
                return this.nombenredField;
            }
            set {
                this.nombenredField = value;
            }
        }
        
        /// <remarks/>
        public int numbencta {
            get {
                return this.numbenctaField;
            }
            set {
                this.numbenctaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numbenctaSpecified {
            get {
                return this.numbenctaFieldSpecified;
            }
            set {
                this.numbenctaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long numplastico {
            get {
                return this.numplasticoField;
            }
            set {
                this.numplasticoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numplasticoSpecified {
            get {
                return this.numplasticoFieldSpecified;
            }
            set {
                this.numplasticoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pan {
            get {
                return this.panField;
            }
            set {
                this.panField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta_CECL0TC))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class Respuesta {
        
        private string claveFinField;
        
        private string claveInicioField;
        
        private string descRetornoField;
        
        private string indMasDatosField;
        
        private string pantPaginaField;
        
        private string retornoField;
        
        private string securityTokenField;
        
        private string tiempoEjecucionField;
        
        private int totalRegistrosField;
        
        private bool totalRegistrosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveFin {
            get {
                return this.claveFinField;
            }
            set {
                this.claveFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveInicio {
            get {
                return this.claveInicioField;
            }
            set {
                this.claveInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descRetorno {
            get {
                return this.descRetornoField;
            }
            set {
                this.descRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string indMasDatos {
            get {
                return this.indMasDatosField;
            }
            set {
                this.indMasDatosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pantPagina {
            get {
                return this.pantPaginaField;
            }
            set {
                this.pantPaginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string securityToken {
            get {
                return this.securityTokenField;
            }
            set {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tiempoEjecucion {
            get {
                return this.tiempoEjecucionField;
            }
            set {
                this.tiempoEjecucionField = value;
            }
        }
        
        /// <remarks/>
        public int totalRegistros {
            get {
                return this.totalRegistrosField;
            }
            set {
                this.totalRegistrosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalRegistrosSpecified {
            get {
                return this.totalRegistrosFieldSpecified;
            }
            set {
                this.totalRegistrosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smu/xsd")]
    public partial class Respuesta_CECL0TC : Respuesta {
        
        private Respuesta_CECL0TC_Registro_CECL0TC[] contratosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contratos", IsNullable=true)]
        public Respuesta_CECL0TC_Registro_CECL0TC[] contratos {
            get {
                return this.contratosField;
            }
            set {
                this.contratosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entrada_CECL0TC))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class EntradaExtendida {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smu/xsd")]
    public partial class Entrada_CECL0TC : EntradaExtendida {
        
        private string centaltaField;
        
        private string cuentaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string centalta {
            get {
                return this.centaltaField;
            }
            set {
                this.centaltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void runServiceCompletedEventHandler(object sender, runServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class runServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal runServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta_CECL0TC Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta_CECL0TC)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void echo_ServiceCompletedEventHandler(object sender, echo_ServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class echo_ServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal echo_ServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591