//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TecnocomWrapper.unicard.sdk.BusquedaPersonasPorPan {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CE_CECO0P2_v10Soap11Binding", Namespace="http://bci")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegistroNewAge))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntradaExtendida))]
    public partial class CE_CECO0P2_v10 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback echo_ServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback runServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CE_CECO0P2_v10() {
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event echo_ServiceCompletedEventHandler echo_ServiceCompleted;
        
        /// <remarks/>
        public event runServiceCompletedEventHandler runServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:echo_Service", RequestNamespace="http://bci", ResponseNamespace="http://bci", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public string echo_Service() {
            object[] results = this.Invoke("echo_Service", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void echo_ServiceAsync() {
            this.echo_ServiceAsync(null);
        }
        
        /// <remarks/>
        public void echo_ServiceAsync(object userState) {
            if ((this.echo_ServiceOperationCompleted == null)) {
                this.echo_ServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.Onecho_ServiceOperationCompleted);
            }
            this.InvokeAsync("echo_Service", new object[0], this.echo_ServiceOperationCompleted, userState);
        }
        
        private void Onecho_ServiceOperationCompleted(object arg) {
            if ((this.echo_ServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.echo_ServiceCompleted(this, new echo_ServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:runService", RequestNamespace="http://bci", ResponseNamespace="http://bci", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public Respuesta_CECO0P2 runService([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] OperationData opData, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Entrada_CECO0P2 eEntrada) {
            object[] results = this.Invoke("runService", new object[] {
                        opData,
                        eEntrada});
            return ((Respuesta_CECO0P2)(results[0]));
        }
        
        /// <remarks/>
        public void runServiceAsync(OperationData opData, Entrada_CECO0P2 eEntrada) {
            this.runServiceAsync(opData, eEntrada, null);
        }
        
        /// <remarks/>
        public void runServiceAsync(OperationData opData, Entrada_CECO0P2 eEntrada, object userState) {
            if ((this.runServiceOperationCompleted == null)) {
                this.runServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrunServiceOperationCompleted);
            }
            this.InvokeAsync("runService", new object[] {
                        opData,
                        eEntrada}, this.runServiceOperationCompleted, userState);
        }
        
        private void OnrunServiceOperationCompleted(object arg) {
            if ((this.runServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.runServiceCompleted(this, new runServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class OperationData {
        
        private bool avanzarField;
        
        private bool avanzarFieldSpecified;
        
        private string canalField;
        
        private string claveFinField;
        
        private string claveInicioField;
        
        private string entidadField;
        
        private string idiomaField;
        
        private string pantPaginaField;
        
        private bool retrocederField;
        
        private bool retrocederFieldSpecified;
        
        private string securityHashField;
        
        /// <remarks/>
        public bool avanzar {
            get {
                return this.avanzarField;
            }
            set {
                this.avanzarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avanzarSpecified {
            get {
                return this.avanzarFieldSpecified;
            }
            set {
                this.avanzarFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveFin {
            get {
                return this.claveFinField;
            }
            set {
                this.claveFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveInicio {
            get {
                return this.claveInicioField;
            }
            set {
                this.claveInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string entidad {
            get {
                return this.entidadField;
            }
            set {
                this.entidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pantPagina {
            get {
                return this.pantPaginaField;
            }
            set {
                this.pantPaginaField = value;
            }
        }
        
        /// <remarks/>
        public bool retroceder {
            get {
                return this.retrocederField;
            }
            set {
                this.retrocederField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool retrocederSpecified {
            get {
                return this.retrocederFieldSpecified;
            }
            set {
                this.retrocederFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string securityHash {
            get {
                return this.securityHashField;
            }
            set {
                this.securityHashField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta_CECO0P2_Registro_CECO0P2))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class RegistroNewAge {
        
        private int registro_NumeroField;
        
        private bool registro_NumeroFieldSpecified;
        
        /// <remarks/>
        public int registro_Numero {
            get {
                return this.registro_NumeroField;
            }
            set {
                this.registro_NumeroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool registro_NumeroSpecified {
            get {
                return this.registro_NumeroFieldSpecified;
            }
            set {
                this.registro_NumeroFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bci/xsd")]
    public partial class Respuesta_CECO0P2_Registro_CECO0P2 : RegistroNewAge {
        
        private string apelargoField;
        
        private string apelli1Field;
        
        private string apelli2Field;
        
        private string codaptcorField;
        
        private string codpostalField;
        
        private string codprovField;
        
        private string desprovField;
        
        private string identcliField;
        
        private string nivsegField;
        
        private string nombreField;
        
        private string nomcompField;
        
        private string nomlargoField;
        
        private string nomviaField;
        
        private string numdocField;
        
        private string numviaField;
        
        private string razsocField;
        
        private string tipdocField;
        
        private string tipperField;
        
        private string tipviaField;
        
        private string viacompField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apelargo {
            get {
                return this.apelargoField;
            }
            set {
                this.apelargoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apelli1 {
            get {
                return this.apelli1Field;
            }
            set {
                this.apelli1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string apelli2 {
            get {
                return this.apelli2Field;
            }
            set {
                this.apelli2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codaptcor {
            get {
                return this.codaptcorField;
            }
            set {
                this.codaptcorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codpostal {
            get {
                return this.codpostalField;
            }
            set {
                this.codpostalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string codprov {
            get {
                return this.codprovField;
            }
            set {
                this.codprovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string desprov {
            get {
                return this.desprovField;
            }
            set {
                this.desprovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string identcli {
            get {
                return this.identcliField;
            }
            set {
                this.identcliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nivseg {
            get {
                return this.nivsegField;
            }
            set {
                this.nivsegField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nomcomp {
            get {
                return this.nomcompField;
            }
            set {
                this.nomcompField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nomlargo {
            get {
                return this.nomlargoField;
            }
            set {
                this.nomlargoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nomvia {
            get {
                return this.nomviaField;
            }
            set {
                this.nomviaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numdoc {
            get {
                return this.numdocField;
            }
            set {
                this.numdocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string numvia {
            get {
                return this.numviaField;
            }
            set {
                this.numviaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string razsoc {
            get {
                return this.razsocField;
            }
            set {
                this.razsocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipdoc {
            get {
                return this.tipdocField;
            }
            set {
                this.tipdocField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipper {
            get {
                return this.tipperField;
            }
            set {
                this.tipperField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tipvia {
            get {
                return this.tipviaField;
            }
            set {
                this.tipviaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string viacomp {
            get {
                return this.viacompField;
            }
            set {
                this.viacompField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Respuesta_CECO0P2))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class Respuesta {
        
        private string claveFinField;
        
        private string claveInicioField;
        
        private string descRetornoField;
        
        private string indMasDatosField;
        
        private string pantPaginaField;
        
        private string retornoField;
        
        private string securityTokenField;
        
        private string tiempoEjecucionField;
        
        private int totalRegistrosField;
        
        private bool totalRegistrosFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveFin {
            get {
                return this.claveFinField;
            }
            set {
                this.claveFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveInicio {
            get {
                return this.claveInicioField;
            }
            set {
                this.claveInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string descRetorno {
            get {
                return this.descRetornoField;
            }
            set {
                this.descRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string indMasDatos {
            get {
                return this.indMasDatosField;
            }
            set {
                this.indMasDatosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pantPagina {
            get {
                return this.pantPaginaField;
            }
            set {
                this.pantPaginaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string securityToken {
            get {
                return this.securityTokenField;
            }
            set {
                this.securityTokenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string tiempoEjecucion {
            get {
                return this.tiempoEjecucionField;
            }
            set {
                this.tiempoEjecucionField = value;
            }
        }
        
        /// <remarks/>
        public int totalRegistros {
            get {
                return this.totalRegistrosField;
            }
            set {
                this.totalRegistrosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalRegistrosSpecified {
            get {
                return this.totalRegistrosFieldSpecified;
            }
            set {
                this.totalRegistrosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bci/xsd")]
    public partial class Respuesta_CECO0P2 : Respuesta {
        
        private Respuesta_CECO0P2_Registro_CECO0P2[] contratosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contratos", IsNullable=true)]
        public Respuesta_CECO0P2_Registro_CECO0P2[] contratos {
            get {
                return this.contratosField;
            }
            set {
                this.contratosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entrada_CECO0P2))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mensajeria/xsd")]
    public partial class EntradaExtendida {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bci/xsd")]
    public partial class Entrada_CECO0P2 : EntradaExtendida {
        
        private string panField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pan {
            get {
                return this.panField;
            }
            set {
                this.panField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void echo_ServiceCompletedEventHandler(object sender, echo_ServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class echo_ServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal echo_ServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void runServiceCompletedEventHandler(object sender, runServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class runServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal runServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Respuesta_CECO0P2 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Respuesta_CECO0P2)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591